/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicoSlugRouteImport } from './routes/servico.$slug'
import { Route as PagamentoCodeRouteImport } from './routes/pagamento.$code'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoSlugRoute = ServicoSlugRouteImport.update({
  id: '/servico/$slug',
  path: '/servico/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoCodeRoute = PagamentoCodeRouteImport.update({
  id: '/pagamento/$code',
  path: '/pagamento/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/pagamento/$code' | '/servico/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/pagamento/$code' | '/servico/$slug'
  id: '__root__' | '/' | '/auth' | '/pagamento/$code' | '/servico/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PagamentoCodeRoute: typeof PagamentoCodeRoute
  ServicoSlugRoute: typeof ServicoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico/$slug': {
      id: '/servico/$slug'
      path: '/servico/$slug'
      fullPath: '/servico/$slug'
      preLoaderRoute: typeof ServicoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$code': {
      id: '/pagamento/$code'
      path: '/pagamento/$code'
      fullPath: '/pagamento/$code'
      preLoaderRoute: typeof PagamentoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PagamentoCodeRoute: PagamentoCodeRoute,
  ServicoSlugRoute: ServicoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
